releases:
  - name: US Consumer Price Index
    release_id: 10
    country: United States
  - name: US Gross Domestic Product
    release_id: 53
    country: United States
  - name: US Employment Situation
    release_id: 50
    country: United States
